### ISSUE TITLE
can u help me in a complete tutorial ?

### ISSUE THREAD

**Issue by remon** [RKushnir/mailboxer-app#1]
I just need a simple tutorial not a complete example as I am not using less and I am using rails 3.2.1 and ruby 1.87
regards

**Comment by RKushnir** [comment]
Sure. I believe the example should be pretty easy to understand as I implemented just the very minimum. But if you have questions tell me what exactly you don't understand? There's nothing special in the model, so is it controller or the rendering part?

**Comment by remon** [comment]
actually I am not using less and I am using only rails 3.2.1...I need only how to implement it with an application ,user authenticated with Devise ,,and each user have one profile ,,I need to implement the gem with the profile model ..thanks for your help

**Comment by remon** [comment]
thanks now..my problem solved ,,the only issue as I am not very good in haml ..how can I show the name of msg sender ,after the msg in the conversations index ,...

**Comment by RKushnir** [comment]
The conversation doesn't store the sender in its model as each message has its own sender. So you can get the first message in the conversation and then take the sender from it.
In controller:

```
receipts = conversation.receipts_for(current_user)
message = receipts.first.message
sender =  message.sender
```

Then in `_conversation.html.haml`:

```
= link_to "#{conversation.subject} by #{sender.name}", conversation
```

The code is not very precise but I hope you get the idea.

**Comment by remon** [comment]
I got your Idea to fetch the sender from the conversation itself ,,but in which action I should put that code ?

**Comment by RKushnir** [comment]
Hi,
I thought you were talking about `conversations#index` action, did I understand you wrong?

**Comment by remon** [comment]
yes you are right ..and what about showing the message send in the conversation action ?

**Comment by remon** [comment]
and sorry I forgot ,,in your example there is not conversation index action

**Comment by RKushnir** [comment]
The `index` action is there, it just doesn't contain any logic, so I didn't include it in the controller, but you can find the `index.html` in the `app/views/conversations`.

To show the messages(and senders) on the conversation page, use the method `receipts_for` - it gets the list of references to messages for current user, like this:

In controller:

```
@messages = conversation.receipts_for(current_user).map{|r| r.message }
```

In `conversations/show.html.haml`:

```
%ul    
  - @messages.each do |message|
    %li
      Message from #{message.sender.name}:
      = message.body
```

**Comment by remon** [comment]
code for show action is working good ,,but the other one for index action is not working ,can you test it?
