### ISSUE TITLE
Switching to ERB

### ISSUE THREAD

**Issue by rsiddle** [RKushnir/mailboxer-app#2]
Hi RKushnir,

I'm looking to change over to the ERB layout for this gem. In the conversations#index view there are three lines of code that I can't fathom out. I'm looking to write my own views for each of the boxes but I can't find the three partials that are used:

%ul= render mailbox.inbox

%ul= render mailbox.sentbox

%ul= render mailbox.trash

Thanks,

Ryan

**Comment by RKushnir** [comment]
Hi Ryan,

`inbox`, `sentbox` and `trash` are a bit cryptic names. In fact, they are just arrays of `Conversation` objects. So those 3 lines above are really just Rails-shortcuts to:

```
= render collection: mailbox.inbox, partial: 'conversations/conversation', as: :conversation
```

Or if you prefer the explicit loop:

```
- mailbox.inbox.each do |conversation|
  = render partial: 'conversations/conversation', object: conversation
```

Hope that helps.
Roman

**Comment by rsiddle** [comment]
Hi Roman,

Thank you for your quick response. That seems to have worked perfectly.

Thqnks,

Ryan

**Comment by rsiddle** [comment]
Hi Roman,

Is it possible to display the user's name who created the conversation within the conversations/conversation partial?

I can't seem to find any helpers such as conversation.sender or conversation.sender_id ? The conversation should be attached to the User model shouldn't it?

Thanks again,

Ryan

**Comment by RKushnir** [comment]
Hi Ryan,

just take the sender of the first message in the conversation. `mailboxer` assumes conversation doesn't belong to any particular sender, but rather to all its participators.

**Comment by rsiddle** [comment]
Hi Roman,

How do we actually reference the first message though? I'm trying:

<% if current_user.mailbox.inbox.any? %>
   <% current_user.mailbox.inbox.each do |conversation| %>
      <%= render partial: 'conversations/conversation', object: conversation %>
    <% end %>
<% end %>

And then in the conversation

<%= content_tag_for(:tr, conversation) do |conversation| %>
  <%= conversation.message.first.sender %>
<% end %>

Thanks again,

Ryan

**Comment by RKushnir** [comment]
@wsmedia I guess you have a typo, `message` should be `messages`.

**Comment by rsiddle** [comment]
Ah yes! Sorry about that
